version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: achei-voce-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: achei_voce_no_google
    ports:
      - "5432:5432"
    volumes:
      - achei_voce_db_data:/var/lib/postgresql/data

volumes:
  achei_voce_db_data:
